version: "3"
services:
  python-backend:
    container_name: codepub-container-workshop-react-backend
    build:
      dockerfile: 00-initial-setup/backend/backend.dockerfile
      context: .
    ports:
      - "8000:8000"
    networks:
      - mynet
  python-frontend:
    container_name: codepub-container-workshop-react-frontend
    build:
      dockerfile: 00-initial-setup/frontend/dockerfile
      context: .
    ports:
      - "3000:3000"
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
