version: "3"
services: 
  frontend:
    build:
      dockerfile: dockerfile
      context: applications/frontend
  backend: 
    build:
      dockerfile: backend.dockerfile
      context: applications/backend