version: '3'
services: 
  python-backend:
    container_name: python-backend
    build: 
      context: './backend'
      dockerfile: Dockerfile
    command: /bin/bash
    tty: true
    ports: 
    - "8081:3000"
    networks: 
    - mynet
  python-frontend: 
    container_name: codepub-container-workshop-python-frontend
    build: 
      context: './frontend'
      dockerfile: Dockerfile 
    ports:
    - "8080:5000"
    networks:
    - mynet

networks:
  mynet: 
    driver: bridge
    ipam: 
      driver: default